language: python
python:
  - "2.7"
  - "3.4"

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  - sudo apt-get update
  - sudo apt-get install libboost1.54-all-dev
  - sudo apt-get install -qq g++-4.8
  - export CC="g++-4.8"

install:
  - pip install -r requirements.txt
  - python setup.py -q install

script: py.test --pyargs py2cpp
